"""
IMDb Top 250 – Interactive Dashboard
--------------------------------------
Run with: streamlit run dashboard.py
Reads from data/imdb_top250_latest.csv (generated by imdb_scraper.py)
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os
from datetime import datetime

# ──────────────────────────────────────────────
# PAGE CONFIG
# ──────────────────────────────────────────────
st.set_page_config(
    page_title="IMDb Top 250 Analyser",
    page_icon="🎬",
    layout="wide",
)

st.title("🎬 IMDb Top 250 — Movie Analytics Dashboard")
st.caption("Data scraped live from IMDb using Selenium · Refresh by re-running the scraper")

# ──────────────────────────────────────────────
# LOAD DATA
# ──────────────────────────────────────────────
DATA_PATH = "data/imdb_top250_latest.csv"

@st.cache_data
def load_data(path):
    df = pd.read_csv(path)
    df["year_num"] = pd.to_numeric(df["year"].astype(str).str.extract(r"(\d{4})")[0], errors="coerce")
    df["decade"]   = df["year_num"].apply(lambda y: f"{int(y)//10*10}s" if pd.notna(y) else None)
    return df

if not os.path.exists(DATA_PATH):
    st.warning("⚠️ No data found. Please run `python imdb_scraper.py` first.")
    st.stop()

df = load_data(DATA_PATH)
scraped_date = df["scraped_date"].iloc[0] if "scraped_date" in df.columns else "Unknown"

st.info(f"📅 Last scraped: **{scraped_date}** · {len(df)} movies loaded")

# ──────────────────────────────────────────────
# SIDEBAR FILTERS
# ──────────────────────────────────────────────
st.sidebar.header("🔍 Filters")

min_rating = st.sidebar.slider("Minimum Rating", 8.0, 9.5, 8.0, 0.1)

# Handle NaN values in year_num
year_valid = df["year_num"].dropna()
if len(year_valid) > 0:
    year_min = int(year_valid.min())
    year_max = int(year_valid.max())
else:
    year_min = 1900
    year_max = 2030

year_range = st.sidebar.slider(
    "Year Range",
    year_min, year_max,
    (1950, year_max)
)
top_n = st.sidebar.selectbox(
    "Show Top N Movies",
    [10, 25, 50, 100, 250],
    index=1,
    format_func=lambda x: f"Top {x} Movies"
)
search_query = st.sidebar.text_input("🔎 Search Movie Title")

# Apply filters
filtered = df[
    (df["rating"] >= min_rating) &
    (df["year_num"] >= year_range[0]) &
    (df["year_num"] <= year_range[1])
].head(top_n)

if search_query:
    filtered = filtered[filtered["title"].str.contains(search_query, case=False, na=False)]

# ──────────────────────────────────────────────
# KPI CARDS
# ──────────────────────────────────────────────
col1, col2, col3, col4 = st.columns(4)
col1.metric("🎥 Total Movies", len(filtered))
avg_rating = f"{filtered['rating'].mean():.2f}" if len(filtered) > 0 else "N/A"
col2.metric("⭐ Avg Rating", avg_rating)
col3.metric("🏆 Highest Rated", filtered.iloc[0]["title"] if len(filtered) > 0 else "N/A")
top_decade = "N/A"
if "decade" in filtered.columns:
    decade_counts = filtered["decade"].value_counts()
    top_decade = decade_counts.idxmax() if not decade_counts.empty else "N/A"
col4.metric("📅 Most Represented Decade", top_decade)

st.divider()

# ──────────────────────────────────────────────
# ROW 1: Top Movies Bar Chart + Decade Pie
# ──────────────────────────────────────────────
col_left, col_right = st.columns([2, 1])

with col_left:
    st.subheader(f"Top {min(top_n, 20)} Movies by Rating")
    top20 = filtered.head(20).sort_values("rating")
    if len(top20) > 0:
        fig = px.bar(
            top20, x="rating", y="title", orientation="h",
            color="rating", color_continuous_scale="Viridis",
            labels={"rating": "IMDb Rating", "title": "Movie"},
        )
        fig.update_layout(height=500, showlegend=False, yaxis_title="")
        st.plotly_chart(fig, width='stretch')
    else:
        st.warning("No movies to display")

with col_right:
    st.subheader("Movies per Decade")
    decade_data = filtered["decade"].dropna().value_counts().sort_index().reset_index()
    if len(decade_data) > 0:
        # Handle different pandas versions with different column names
        if "count" in decade_data.columns:
            decade_data.columns = ["Decade", "Count"]
        elif "decade" in decade_data.columns:
            decade_data = decade_data.rename(columns={list(decade_data.columns)[1]: "Count"})
        
        fig2 = px.pie(
            decade_data, values="Count", names="Decade",
            hole=0.4, color_discrete_sequence=px.colors.sequential.RdBu
        )
        fig2.update_layout(height=500)
        st.plotly_chart(fig2, width='stretch')
    else:
        st.warning("No decade data available")

st.divider()

# ──────────────────────────────────────────────
# ROW 2: Rating Distribution + Rank vs Rating
# ──────────────────────────────────────────────
col3, col4 = st.columns(2)

with col3:
    st.subheader("Rating Distribution")
    fig3 = px.histogram(
        filtered, x="rating", nbins=20,
        color_discrete_sequence=["#f5c518"],
        labels={"rating": "IMDb Rating", "count": "Number of Movies"}
    )
    st.plotly_chart(fig3, width='stretch')

with col4:
    st.subheader("Rank vs Rating Scatter")
    fig4 = px.scatter(
        filtered, x="rank", y="rating",
        hover_name="title", hover_data=["year"],
        color="rating", color_continuous_scale="Cividis",
        labels={"rank": "IMDb Rank", "rating": "IMDb Rating"}
    )
    fig4.update_layout(xaxis_autorange="reversed")
    st.plotly_chart(fig4, width='stretch')

st.divider()

# ──────────────────────────────────────────────
# ROW 3: Rating Timeline
# ──────────────────────────────────────────────
st.subheader("📅 Average Rating Over the Decades")
timeline = filtered.dropna(subset=["year_num", "decade"]).groupby("decade")["rating"].mean().reset_index()
if len(timeline) > 0:
    if "decade" in timeline.columns:
        timeline = timeline.rename(columns={"decade": "Decade", "rating": "Avg Rating"} if "decade" in timeline.columns else {})
    # Ensure correct column names
    timeline.columns = ["Decade", "Avg Rating"]
    fig5 = px.line(
        timeline, x="Decade", y="Avg Rating",
        markers=True, line_shape="spline",
        color_discrete_sequence=["#f5c518"]
    )
    fig5.update_layout(yaxis_range=[8, 9.5])
    st.plotly_chart(fig5, width='stretch')
else:
    st.warning("No timeline data available (insufficient year data)")

st.divider()

# ──────────────────────────────────────────────
# DATA TABLE
# ──────────────────────────────────────────────
st.subheader("📋 Full Data Table")
display_cols = ["rank", "title", "year", "rating", "votes", "duration"]
available_cols = [c for c in display_cols if c in filtered.columns]
st.dataframe(
    filtered[available_cols].reset_index(drop=True),
    width='stretch',
    height=400
)

# Download button
csv = filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Download Filtered CSV",
    data=csv,
    file_name=f"imdb_filtered_{datetime.now().strftime('%Y%m%d')}.csv",
    mime="text/csv"
)

# ──────────────────────────────────────────────
# TREND COMPARISON (if multiple snapshots exist)
# ──────────────────────────────────────────────
st.divider()
st.subheader("📈 Trend Comparison (Multi-Snapshot)")

data_dir = "data"
snapshots = sorted([
    f for f in os.listdir(data_dir)
    if f.startswith("imdb_top250_2") and f.endswith(".csv")
]) if os.path.exists(data_dir) else []

if len(snapshots) >= 2:
    col_s1, col_s2 = st.columns(2)
    snap1 = col_s1.selectbox("Older snapshot", snapshots, index=0)
    snap2 = col_s2.selectbox("Newer snapshot", snapshots, index=len(snapshots)-1)

    if st.button("Compare Snapshots"):
        df1 = pd.read_csv(os.path.join(data_dir, snap1)).set_index("title")
        df2 = pd.read_csv(os.path.join(data_dir, snap2)).set_index("title")

        common = df1.index.intersection(df2.index)
        if len(common) > 0:
            rank_change = (df1.loc[common, "rank"] - df2.loc[common, "rank"])

            st.markdown("**⬆️ Movies that climbed the most**")
            climbed = rank_change.sort_values(ascending=False).head(10).reset_index()
            # Handle column naming properly
            if len(climbed.columns) >= 2:
                climbed.columns = ["Title"] + climbed.columns[1:].tolist()
                if climbed.columns[1] != "Rank Improvement":
                    climbed.rename(columns={climbed.columns[1]: "Rank Improvement"}, inplace=True)
            st.dataframe(climbed)

            st.markdown("**⬇️ Movies that dropped the most**")
            dropped_df = rank_change.sort_values(ascending=True).head(10).reset_index()
            # Handle column naming properly
            if len(dropped_df.columns) >= 2:
                dropped_df.columns = ["Title"] + dropped_df.columns[1:].tolist()
                if dropped_df.columns[1] != "Rank Drop":
                    dropped_df.rename(columns={dropped_df.columns[1]: "Rank Drop"}, inplace=True)
            st.dataframe(dropped_df)

            new_in  = list(df2.index.difference(df1.index))
            dropped = list(df1.index.difference(df2.index))
            st.markdown(f"**🆕 New entrants:** {new_in[:5] if new_in else 'None'}")
            st.markdown(f"**❌ Dropped out:** {dropped[:5] if dropped else 'None'}")
        else:
            st.warning("No common movies between the two snapshots.")
else:
    st.info("Run the scraper on multiple days to unlock trend comparison.")

st.caption("Built with Selenium · pandas · Streamlit · Plotly")
